Help Button Cube Ballz
Tech-Tac/cubes pull request #3
Opened 2024-11-04 18:16 UTC by Sleet827

Help Button but now it's both Cubes and Ballz

2024-11-04 18:50 UTC, Tech-Tac requested changes

2024-11-04 18:50 UTC, Tech-Tac commented on index.html
> +          <p>Make 3D builds out of little <span id="helpBtnCubeBallz">cubes</span>, you can change cube colors, view from a different angle, and save/share your build!</p>
Unprofessional id naming

2024-11-04 18:50 UTC, Tech-Tac commented on index.js
> +    document.getElementById("helpBtnCubeBallz").innerHTML = "balls";
Same goes here

2024-11-05 12:03 UTC, Sleet827 commented on index.html
> +          <p>Make 3D builds out of little <span id="helpBtnCubeBallz">cubes</span>, you can change cube colors, view from a different angle, and save/share your build!</p>
nerd

2024-11-05 12:03 UTC, Sleet827 commented on index.js
> +    document.getElementById("helpBtnCubeBallz").innerHTML = "balls";
nerd

2024-11-05 14:45 UTC, merged

2024-11-05 14:46 UTC, Tech-Tac commented
done